In [1]:
strText = input("아무 문장이나 입력하세요 : ")
print(strText)

아무 문장이나 입력하세요 : 테스트
테스트


In [2]:
flVal = [1.0, 2.0, 3.14, 4.2, 5.1]

In [3]:
arVal = [flVal, flVal, flVal]
arVal

[[1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1]]

In [4]:
arVal[0]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [5]:
arVal[1]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [6]:
arVal[1][2]

3.14

In [7]:
arVal[0] = 'python'
arVal

['python', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [8]:
arVal[0][2]

't'

In [10]:
arVal[0] = 'python programming'
arVal

['python programming', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [11]:
import numpy as np
arData = np.array([1.0, 2.0, 3.14, 4.2, 5.1])
arData

array([1.  , 2.  , 3.14, 4.2 , 5.1 ])

In [12]:
arData.sum()

15.44

In [13]:
arVal.sum()

AttributeError: 'list' object has no attribute 'sum'

In [14]:
print(type(arVal))
print(type(arData))

<class 'list'>
<class 'numpy.ndarray'>


In [15]:
arData.std()

1.4717934637713266

In [16]:
arData.cumsum()

array([ 1.  ,  3.  ,  6.14, 10.34, 15.44])

In [17]:
arData * 2

array([ 2.  ,  4.  ,  6.28,  8.4 , 10.2 ])

In [18]:
arData ** 2

array([ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ])

In [19]:
np.sqrt(arData)

array([1.        , 1.41421356, 1.77200451, 2.04939015, 2.25831796])

In [20]:
arVal = np.array([arData, arData ** 2])
arVal

array([[ 1.    ,  2.    ,  3.14  ,  4.2   ,  5.1   ],
       [ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ]])

In [21]:
arVal.sum(axis=0)

array([ 2.    ,  6.    , 12.9996, 21.84  , 31.11  ])

In [22]:
arVal.sum(axis=1)

array([15.44  , 58.5096])

In [23]:
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [27]:
arZero = np.zeros((2,3), dtype = 'i') 
arZero

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [28]:
import pandas as pd

pandas_series = pd.Series([30, 20, 10], index=['국어', '영어', '수학'])
print(type(pandas_series))
pandas_series

<class 'pandas.core.series.Series'>


국어    30
영어    20
수학    10
dtype: int64

In [29]:
pandas_series[1:]

영어    20
수학    10
dtype: int64

In [30]:
pandas_series[0]

30

In [31]:
pandas_series[0][1]

IndexError: invalid index to scalar variable.

In [32]:
df = pd.DataFrame([30,20,10], columns=['score'], index=['국어', '영어', '수학'])
df

score
국어     30
영어     20
수학     10

In [33]:
df.index

Index(['국어', '영어', '수학'], dtype='object')

In [34]:
df.columns

Index(['score'], dtype='object')

In [35]:
df.loc['국어']

score    30
Name: 국어, dtype: int64

In [36]:
df.sum()

score    60
dtype: int64

In [37]:
df.score ** 2

국어    900
영어    400
수학    100
Name: score, dtype: int64

In [38]:
df['score2'] = (50, 50, 50)
df

score  score2
국어     30      50
영어     20      50
수학     10      50

In [39]:
df['score2'] = pd.DataFrame([90,90,90], index=['국어', '영어', '수학'])
df

score  score2
국어     30      90
영어     20      90
수학     10      90

In [40]:
del df['score']

In [41]:
df['score2'] = (90, 90, 90, 100)

ValueError: Length of values (4) does not match length of index (3)

In [42]:
df['score2'] = pd.DataFrame([90, 90, 90, 100], index=['국어', '영어', '수학', '윤리'])
df

score2
국어      90
영어      90
수학      90

In [46]:
df1 = pd.DataFrame([1, 2, 3], columns = ['A'])
df2 = pd.DataFrame([10, 11, 12, 13], columns = ['B'])
df = df1.join(df2, how='outer')
df

A   B
0  1.0  10
1  2.0  11
2  3.0  12
3  NaN  13

In [47]:
df_inner = df1.join(df2, how='inner')
df_inner

A   B
0  1  10
1  2  11
2  3  12

In [48]:
df = pd.DataFrame(np.random.randn(5,5))
df.columns = ['A', 'B', 'C', 'D', 'E']
df

A         B         C         D         E
0  1.131690 -1.316355  0.754128  0.392601 -0.769570
1 -0.492990 -2.678652  2.028033  0.159147 -0.116792
2 -0.547956  1.633414  0.041724  0.443543  0.134334
3 -1.820444 -0.094928 -0.027724  1.569535 -1.404467
4 -2.134295  0.784249  1.412531 -1.008646 -0.546059

In [49]:
df.max()

A    1.131690
B    1.633414
C    2.028033
D    1.569535
E    0.134334
dtype: float64

In [50]:
df.min()

A   -2.134295
B   -2.678652
C   -0.027724
D   -1.008646
E   -1.404467
dtype: float64

In [51]:
df.mean()

A   -0.772799
B   -0.334454
C    0.841738
D    0.311236
E   -0.540511
dtype: float64

In [52]:
df.std()

A    1.294909
B    1.705928
C    0.885545
D    0.918240
E    0.598722
dtype: float64

In [55]:
df.cumsum()

A         B         C         D         E
0  1.131690 -1.316355  0.754128  0.392601 -0.769570
1  0.638700 -3.995007  2.782160  0.551748 -0.886362
2  0.090744 -2.361593  2.823884  0.995291 -0.752028
3 -1.729701 -2.456521  2.796160  2.564826 -2.156496
4 -3.863996 -1.672272  4.208691  1.556180 -2.702555

In [56]:
df.describe()

A         B         C         D         E
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean  -0.772799 -0.334454  0.841738  0.311236 -0.540511
std    1.294909  1.705928  0.885545  0.918240  0.598722
min   -2.134295 -2.678652 -0.027724 -1.008646 -1.404467
25%   -1.820444 -1.316355  0.041724  0.159147 -0.769570
50%   -0.547956 -0.094928  0.754128  0.392601 -0.546059
75%   -0.492990  0.784249  1.412531  0.443543 -0.116792
max    1.131690  1.633414  2.028033  1.569535  0.134334

In [57]:
df['division'] = ['X', 'Y', 'X', 'Y', 'Z']
df

A         B         C         D         E division
0  1.131690 -1.316355  0.754128  0.392601 -0.769570        X
1 -0.492990 -2.678652  2.028033  0.159147 -0.116792        Y
2 -0.547956  1.633414  0.041724  0.443543  0.134334        X
3 -1.820444 -0.094928 -0.027724  1.569535 -1.404467        Y
4 -2.134295  0.784249  1.412531 -1.008646 -0.546059        Z

In [58]:
df.groupby(['division']).mean()

A         B         C         D         E
division                                                  
X         0.291867  0.158529  0.397926  0.418072 -0.317618
Y        -1.156717 -1.386790  1.000155  0.864341 -0.760630
Z        -2.134295  0.784249  1.412531 -1.008646 -0.546059